name: Deploy DEV

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Build Js
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          CI: true
        run: |
          npm i
          npm run build
      - uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Use Composer
        uses: php-actions/composer@v6
        with:
          php_version: "8.3"
          version: "2.x"
          quiet: "yes"
          args: "--ignore-platform-reqs --no-dev --no-interaction --no-progress --no-suggest --prefer-dist"
      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.run_id }}
          path: |
            public/build
            vendor
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: DEV
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.run_id }}
          path: .
      - uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rvW --no-compress --delete --delete-excluded"
          SOURCE: "./"
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_HOST: ${{ secrets.SSH_KNOW_HOST }}
          TARGET: ${{ vars.BASE_FOLDER }}${{ vars.TEMP_FOLDER }}
          EXCLUDE:
            "/tests/, /php*, /resources/js/, /resources/css/, /resources/less/, /*.md, /node_modules/, /*.js, /*.png, /*package*, Procfile, /*.git*, /.editor*, /.prettier*"
      - uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_KNOW_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod 700 ${{ vars.BASE_FOLDER }}${{ vars.TEMP_FOLDER }}/deploy.sh
            ${{ vars.BASE_FOLDER }}${{ vars.TEMP_FOLDER }}/deploy.sh ${{ vars.BASE_FOLDER }} ${{ vars.TEMP_FOLDER }} ${{ vars.RELEASE_FOLDER }}
            rm ${{ vars.BASE_FOLDER }}${{ vars.RELEASE_FOLDER }}/deploy.sh
