name: Deploy DEV

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Build Js
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: |
          npm i
          npm run build
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Use Composer
        uses: php-actions/composer@v6
        with:
          php_version: "8.3"
          version: "2.x"
          quiet: "yes"
          args: "--ignore-platform-reqs"
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rvW --no-compress --delete --delete-excluded"
          SOURCE: "./"
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_HOST: ${{ secrets.SSH_KNOW_HOST }}
          TARGET: ${{ vars.BASE_FOLDER }}${{ vars.TEMP_FOLDER }}
          EXCLUDE:
            "/tests/, /DOCKER*, /Docker*, /docker*, /output.log, /phpunit.xml, /resources/js/, /resources/css/, /resources/less/, /docker-compose*, /*.md, /node_modules"
      - uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_KNOW_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod +x ${{ vars.BASE_FOLDER }}${{ vars.TEMP_FOLDER }}/deploy.sh
            ${{ vars.BASE_FOLDER }}${{ vars.TEMP_FOLDER }}/deploy.sh ${{ vars.BASE_FOLDER }} ${{ vars.TEMP_FOLDER }} ${{ vars.RELEASE_FOLDER }}
            rm ${{ vars.RELEASE_FOLDER }}${{ vars.TEMP_FOLDER }}/deploy.sh
